# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Metal³ - Metal Kubed
email: non@none.com
description: >- # this means to ignore newlines until "baseurl:"
   Metal3.io aims to build on baremetal host provisioning technologies to provide a Kubernetes native API for managing bare metal hosts via a provisioning stack that is also running on Kubernetes.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://metal3.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: metal3_io
github_username:  metal3-io
type: website
image: /assets/images/metal3logo.png
highlighter: rouge

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    default_lang: html
    css_class: 'syntax'
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1
theme: minima
plugins:
  - premonition
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-toc

paginate: 5
paginate_path: "/blog/page:num"

collections:
  faqs:
    output: true
  galleries:
    output: true
    permalink: /:collection/:path


sass:
  sass_dir: _sass
  style: compressed


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

exclude:
  - GUIDELINES.md
  - README.md
  - node_modules

permalink: /blog/:year/:month/:day/:title:output_ext

toc:
  min_level: 2
  max_level: 6
  no_toc_section_class: no_toc_section
  list_class: section-nav
  sublist_class: ''
  item_class: toc-entry
  item_prefix: toc-
